---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: sample-app
   namespace: default
 spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: web
     spec:
       containers:
         - name: sample-app
           image: com.iheart/jms-sample
           imagePullPolicy: Never 
           ports:
             - containerPort: 8080
               protocol: TCP
           resources:
             requests:
               cpu: 200m


