apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: queue-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: External
    external:
      metricName: queue_messages_ready
      metricSelector:
        matchLabels:
          name: my-test-queue
      targetAverageValue: 250
